polls/urls.py
from django.conf.urls import patterns, url

from polls import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^specifics/(?P<question_id>\d+)/$', views.detail, name='detail'),
    url(r'^(?P<question_id>\d+)/results/$', views.results, name='results'),
    url(r'^(?P<question_id>\d+)/vote/$', views.vote, name='vote'),
)

pybursa/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.http import HttpResponse

from pybursa import views
from feedbacks.views import FeedbackView

def index(request):
    return HttpResponse('hello')

urlpatterns = patterns('',
    url(r'^polls/', include('polls.urls', namespace="polls")),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', views.index, name='index'),
    url(r'^contact/$', views.contact, name='contact'),
    url(r'^student_list/$', views.student_list, name='student_list'),
    url(r'^student_detail/$', views.student_detail, name='student_detail'),
    url(r'^student_detail/$', views.student_detail, name='student_detail'),
    url(r'^quadratic/', include('quadratic.urls'), name='quadratic'),

    url(r'^courses/', include('courses.urls', namespace="courses")),
    url(r'^/courses/', include('courses.urls', namespace="courses")),
    url(r'^students/', include('students.urls', namespace="students")),
    url(r'^coaches/', include('coaches.urls', namespace="coaches")),

    url(r'^feedback/$', FeedbackView.as_view(), name='feedback'),
)

students/urls.py
from django.conf.urls import patterns, url
from students.views import StudentDetailView, StudentListView, \
    StudentCreateView, StudentUpdateView, StudentDeleteView




urlpatterns = patterns('',
    url(r'^$', StudentListView.as_view(), name='list_view'),
    url(r'^(?P<pk>\d+)/$', StudentDetailView.as_view(), name='detail'),
    url(r'^add/$', StudentCreateView.as_view(), name='add'),
    url(r'^edit/(?P<pk>\d+)/$', StudentUpdateView.as_view(), name='edit'),
    url(r'^remove/(?P<pk>\d+)/$', StudentDeleteView.as_view(), name='remove')
)

students/models.py
from django.db import models

from courses.models import Course

class Student(models.Model):
    name = models.CharField(max_length=100)
    surname = models.CharField(max_length=100)
    date_of_birth = models.DateField()
    email = models.EmailField()
    phone = models.CharField(max_length=60)
    address = models.CharField(max_length=200)
    skype = models.CharField(max_length=100)
    courses = models.ManyToManyField(Course)

    def __unicode__(self):
        return self.surname+' '+self.name

    def _get_full_name(self):
        return self.name+' '+self.surname

    full_name = property(_get_full_name)

students/forms.py
from django import forms

from students.models import Student


class StudentModelForm(forms.ModelForm):

    class Meta:
        model = Student

students/views.py
from django.core.urlresolvers import reverse_lazy
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from students.models import Student
from django.contrib import messages

import logging
student_logger = logging.getLogger(__name__)

class StudentDetailView(DetailView):
    model = Student

    def get_context_data(self, **kwargs):
        #student_logger.debug("Students detail view has been debugged")
        #student_logger.info("Logger of students detail view informs you!")
        #student_logger.warning("Logger of students detail view warns you!")
        #student_logger.error("Students detail view went wrong!")
        return super(StudentDetailView, self).get_context_data(**kwargs)

class StudentListView(ListView):
    model = Student
    template_name = 'students/student_list.html'

    def get_queryset(self):
        course_id = self.request.GET.get('course_id')
        if course_id:
            students = Student.objects.filter(courses=course_id)
        else:
            students = Student.objects.all()

        paginator = Paginator(students, 2)
        page = self.request.GET.get('page')
        try:
            students_list = paginator.page(page)
        except PageNotAnInteger:
            students_list = paginator.page(1)
        except EmptyPage:
            students_list = paginator.page(1)
        return students_list

    def get_context_data(self, **kwargs):
        data = super(StudentListView, self).get_context_data(**kwargs)
        course_id = self.request.GET.get('course_id')
        if not course_id:
            course_link = ''
        else:
            course_link = '&course_id=%s' % course_id
        data['course_link'] = course_link
        return data

class StudentCreateView(CreateView):
    model = Student
    success_url = reverse_lazy('students:list_view')

    def get_context_data(self, **kwargs):
        data = super(StudentCreateView, self).get_context_data(**kwargs)
        data['title'] = 'Student registration'
        return data

    def form_valid(self, form):
        student = form.save()
        messages.success(self.request, 'Student %s %s has been successfully added.' % (student.name, student.surname))
        return super(StudentCreateView, self).form_valid(form)

class StudentUpdateView(UpdateView):
    model = Student
    success_url = reverse_lazy('students:list_view')

    def get_context_data(self, **kwargs):
        data = super(StudentUpdateView, self).get_context_data(**kwargs)
        data['title'] = 'Student info update'
        return data

    def form_valid(self, form):
        form.save()
        messages.success(self.request, 'Info on the student has been sucessfully changed.')
        return super(StudentUpdateView, self).form_valid(form)

    def get_success_url(self):
        return reverse_lazy('students:edit', None, [self.object.id])

class StudentDeleteView(DeleteView):
    model = Student
    success_url = reverse_lazy('students:list_view')

    def get_context_data(self, **kwargs):
        data = super(StudentDeleteView, self).get_context_data(**kwargs)
        data['title'] = 'Student info suppression'
        return data

    def delete(self, request, *args, **kwargs):
        ret_msg = super(StudentDeleteView, self).delete(request, *args, **kwargs)
        messages.success(self.request, 'Info on %s %s has been sucessfully deleted.' % (self.object.name, self.object.surname))
        return ret_msg

templates/students/add.html
{% extends "base.html" %}

{% load staticfiles %}

{% block title %}IT courses add students page{% endblock title %}

{% block navi %}
    {% include "include/navi_include.html" with active_students="active" %}
{% endblock navi %}

{% block content %}

    <div class="page-header">
        <h1 class="user-list-course">Добавить нового студента</h1>
    </div>

    <div class="user-list">

        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Добавить"/>
        </form>

    </div>

{% endblock content %}

templates/students/detail.html
{% extends "base.html" %}

{% load staticfiles %}

{% block title %}IT courses students detail page{% endblock title %}

{% block navi %}
    {% include "include/navi_include.html" with active_students="active" %}
{% endblock navi %}

{% block content %}

    <div class="page-header">
        <h1 class="detail-surname">{{ student.name }} {{ student.surname }}</h1>
    </div>

    <div>
        <table class="table detail-table">
            <tr>
                <th>дата рождения</th>
                <td>{{ student.date_of_birth }}</td>
            </tr>
            <tr>
                <th>адрес</th>
                <td>{{ student.address }}</td>
            </tr>
            <tr>
                <th>почта</th>
                <td>{{ student.email }}</td>
            </tr>
            <tr>
                <th>логин skype</th>
                <td>{{ student.skype }}</td>
            </tr>
            <tr>
                <th>телефон</th>
                <td>{{ student.phone }}</td>
            </tr>
            <tr>
                <th>Курсы</th>
                <td>
                    <ul>
                        {% for course in student.courses.all %}
                        <li><a href="{% url 'courses:detail' course.id %}">{{ course }}</a></li>
                        {% endfor %}
                    </ul>
                </td>
            </tr>
        </table>
    </div>

{% endblock content %}

templates/students/edit.html
{% extends "base.html" %}

{% load staticfiles %}

{% block title %}IT courses edit students page{% endblock title %}

{% block navi %}
    {% include "include/navi_include.html" with active_students="active" %}
{% endblock navi %}

{% block content %}

    <div class="page-header">
        <h1 class="user-list-course">Редактирование студента</h1>
    </div>

    <div class="user-list">

        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Сохранить"/>
        </form>

    </div>

{% endblock content %}

templates/students/list.html
{% extends "base.html" %}

{% load staticfiles %}

{% block title %}IT courses students page{% endblock title %}

{% block navi %}
    {% include "include/navi_include.html" with active_students="active" %}
{% endblock navi %}

{% block content %}

    <div class="page-header">
        <h1 class="user-list-course">Список студентов</h1>
    </div>
    <a href="{% url 'students:add' %}" class="btn btn-info">добавить студента</a>
    <div class="user-list">

        <table>
            <tr>
                <th>#</th>
                <th>Фамилия имя</th>
                <th>адрес</th>
                <th>skype</th>
                <th>курсы</th>
            </tr>
                {% for student in students %}
            <tr>
                <td>{{ student.id }}</td>
                <td>
                    <a href="{% url 'students:detail' student.id %}">{{ student }}</a>
                </td>
                <td>{{ student.address }}</td>
                <td>{{ student.skype }}</td>
                <td>
                    <ul>
                        {% for course in student.courses.all %}
                            <li><a href="{% url 'courses:detail' course.id %}">{{ course }}</a></li>
                        {% endfor %}
                        <li><a href="{% url 'students:edit' student.id %}" class="btn btn-info">Изменить</a></li>
                        <li><a href="{% url 'students:remove' student.id %}" class="btn btn-info">Удалить</a></li>
                    </ul>
                </td>
            </tr>
            {% endfor %}
        </table>

    </div>

{% endblock content %}

templates/students/list_view.html
{% extends "base.html" %}

{% load staticfiles %}

{% block title %}IT courses students page{% endblock title %}

{% block navi %}
    {% include "include/navi_include.html" with active_students="active" %}
{% endblock navi %}

{% block content %}

    <div class="page-header">
        <h1 class="user-list-course">Список студентов</h1>
    </div>

    <div class="user-list">

        <table>
            <tr>
                <th>#</th>
                <th>Фамилия имя</th>
                <th>адрес</th>
                <th>skype</th>
                <th>курсы</th>
            </tr>
                {% for student in students %}
            <tr>
                <td>{{ student.id }}</td>
                <td>
                    <a href="{% url 'students:detail' student.id %}">{{ student }}</a>
                </td>
                <td>{{ student.address }}</td>
                <td>{{ student.skype }}</td>
                <td>
                    <ul>
                        {% for course in student.courses.all %}
                            <li><a href="{% url 'courses:detail' course.id %}">{{ course }}</a></li>
                        {% endfor %}
                    </ul>
                </td>
            </tr>
            {% endfor %}
        </table>

    </div>

{% endblock content %}

templates/students/remove.html
{% extends "base.html" %}

{% load staticfiles %}

{% block title %}IT courses delete students page{% endblock title %}

{% block navi %}
    {% include "include/navi_include.html" with active_students="active" %}
{% endblock navi %}

{% block content %}

    <div class="page-header">
        <h1 class="user-list-course">Список студентов</h1>
    </div>

    <div class="user-list">

        <h4>Студент {{ student.name }} {{ student.surname }} будет удален</h4>
        <form method="post">
            {% csrf_token %}
            <input type="submit" value="Удалить" />
        </form>

    </div>

{% endblock content %}

templates/students/student_confirm_delete.html
{% extends "base.html" %}

{% load staticfiles %}

{% block title %}IT courses delete students page{% endblock title %}

{% block navi %}
    {% include "include/navi_include.html" with active_students="active" %}
{% endblock navi %}

{% block content %}

    <div class="page-header">
        <h1 class="user-list-course">{{ title }}</h1>
    </div>

    <div class="user-list">

        <h4>Студент {{ student.name }} {{ student.surname }} будет удален</h4>
        <form method="post">
            {% csrf_token %}
            <input type="submit" value="Удалить" />
        </form>

    </div>

{% endblock content %}

templates/students/student_detail.html
{% extends "base.html" %}

{% load staticfiles %}

{% block title %}IT courses students detail page{% endblock title %}

{% block navi %}
    {% include "include/navi_include.html" with active_students="active" %}
{% endblock navi %}

{% block content %}

    <!-- Contact Section
    ==========================================-->
    <div id="tf-contact" class="text-center">
        <div class="container">
            <div class="section-title center">
                <h2>{{ student.name }} {{ student.surname }}</h2>
                <div class="line">
                    <hr>
                </div>
                <div class="clearfix"></div>
                <small><em>Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of "de Finibus Bonorum et Malorum" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, "Lorem ipsum dolor sit amet..", comes from a line in section 1.10.32.</em></small>
            </div>

            <table class="table table-striped table-bordered">
                <tr>
                    <th>дата рождения</th>
                    <td>{{ student.date_of_birth }}</td>
                </tr>
                <tr>
                    <th>адрес</th>
                    <td>{{ student.address }}</td>
                </tr>
                <tr>
                    <th>почта</th>
                    <td>{{ student.email }}</td>
                </tr>
                <tr>
                    <th>логин skype</th>
                    <td>{{ student.skype }}</td>
                </tr>
                <tr>
                    <th>телефон</th>
                    <td>{{ student.phone }}</td>
                </tr>
                <tr>
                    <th>Курсы</th>
                    <td>
                        <ul>
                            {% for course in student.courses.all %}
                            <li><a href="{% url 'courses:detail' course.id %}">{{ course }}</a></li>
                            {% endfor %}
                        </ul>
                    </td>
                </tr>
            </table>

        </div>
    </div>

{% endblock content %}

templates/students/student_form.html
{% extends "base.html" %}

{% load staticfiles %}

{% block title %}IT courses add students page{% endblock title %}

{% block navi %}
    {% include "include/navi_include.html" with active_students="active" %}
{% endblock navi %}

{% block content %}

    <!-- Contact Section
    ==========================================-->
    <div id="tf-contact" class="text-center">
        <div class="container">
            <div class="section-title center">
                <h2>{{ title }}</h2>
                <div class="line">
                    <hr>
                </div>
                <div class="clearfix"></div>
                <small><em>Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of "de Finibus Bonorum et Malorum" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, "Lorem ipsum dolor sit amet..", comes from a line in section 1.10.32.</em></small>
            </div>

            <form method="post">
                {% csrf_token %}
                <table class="table table-striped table-bordered">
                    {{ form.as_table }}
                </table>
                <input type="submit" value="Save"/>
            </form>

        </div>
    </div>

{% endblock content %}

templates/students/student_list.html
{% extends "base.html" %}

{% load staticfiles %}

{% block title %}IT courses students page{% endblock title %}

{% block navi %}
    {% include "include/navi_include.html" with active_students="active" %}
{% endblock navi %}

{% block content %}

    <div id="tf-contact" class="text-center">
        <div class="container">

            <div class="row">
                <div class="col-md-8 col-md-offset-2">

                    <div class="section-title center">
                        <h2>Список студентов</h2>
                        <div class="line">
                            <hr>
                        </div>
                        <div class="clearfix"></div>
                        <small><em>Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of "de Finibus Bonorum et Malorum" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, "Lorem ipsum dolor sit amet..", comes from a line in section 1.10.32.</em></small>
                        <a href="{% url 'students:add' %}">добавить студента</a>
                    </div>

                        <table class="table table-striped table-bordered">
                            <tr>
                                <th>#</th>
                                <th>Фамилия имя</th>
                                <th>адрес</th>
                                <th>skype</th>
                                <th>курсы</th>
                            </tr>
                                {% for student in object_list %}
                            <tr>
                                <td>{{ student.id }}</td>
                                <td>
                                    <a href="{% url 'students:detail' student.id %}">{{ student }}</a>
                                </td>
                                <td>{{ student.address }}</td>
                                <td>{{ student.skype }}</td>
                                <td>
                                    <ul>
                                        {% for course in student.courses.all %}
                                            <li><a href="{% url 'courses:detail' course.id %}">{{ course }}</a></li>
                                        {% endfor %}
                                        <li><a href="{% url 'students:edit' student.id %}">Изменить</a></li>
                                        <li><a href="{% url 'students:remove' student.id %}">Удалить</a></li>
                                    </ul>
                                </td>
                            </tr>
                            {% endfor %}
                        </table>

                        <ul class="pagination pagination-centered">
                            {% if object_list.has_previous %}
                                <li><a href="?page={{ object_list.previous_page_number }}{{ course_link }}"><< previous</a></li>
                            {% endif %}
                            <li><a href="#">Page {{ object_list.number }} of {{ object_list.paginator.num_pages }}.</a></li>
                            {% if object_list.has_next %}
                                <li><a href="?page={{ object_list.next_page_number }}{{ course_link }}">next >></a></li>
                            {% endif %}
                        </ul>

                </div>
            </div>

        </div>
    </div>

{% endblock content %}