courses/urls.py
from django.conf.urls import patterns, url

from courses.views import CourseDetailView, CourseCreateView, \
    CourseUpdateView, CourseDeleteView, LessonCreateView

urlpatterns = patterns('',
    url(r'^(?P<pk>\d+)/$', CourseDetailView.as_view(), name='detail'),
    url(r'^add/$', CourseCreateView.as_view(), name='add'),
    url(r'^edit/(?P<pk>\d+)/$', CourseUpdateView.as_view(), name='edit'),
    url(r'^remove/(?P<pk>\d+)/$', CourseDeleteView.as_view(), name='remove'),
    url(r'^(?P<pk>\d+)/add_lesson$', LessonCreateView.as_view(), name='add-lesson')
)

polls/urls.py
from django.conf.urls import patterns, url

from polls import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^specifics/(?P<question_id>\d+)/$', views.detail, name='detail'),
    url(r'^(?P<question_id>\d+)/results/$', views.results, name='results'),
    url(r'^(?P<question_id>\d+)/vote/$', views.vote, name='vote'),
)

pybursa/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.http import HttpResponse

from pybursa import views
from feedbacks.views import FeedbackView

def index(request):
    return HttpResponse('hello')

urlpatterns = patterns('',
    url(r'^polls/', include('polls.urls', namespace="polls")),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', views.index, name='index'),
    url(r'^contact/$', views.contact, name='contact'),
    url(r'^student_list/$', views.student_list, name='student_list'),
    url(r'^student_detail/$', views.student_detail, name='student_detail'),
    url(r'^student_detail/$', views.student_detail, name='student_detail'),
    url(r'^quadratic/', include('quadratic.urls'), name='quadratic'),

    url(r'^courses/', include('courses.urls', namespace="courses")),
    url(r'^/courses/', include('courses.urls', namespace="courses")),
    url(r'^students/', include('students.urls', namespace="students")),
    url(r'^coaches/', include('coaches.urls', namespace="coaches")),

    url(r'^feedback/$', FeedbackView.as_view(), name='feedback'),
)

courses/models.py
from django.db import models
from django.core.urlresolvers import reverse_lazy

from coaches.models import Coach

class Course(models.Model):
    name = models.CharField(max_length=50)
    short_description = models.CharField(max_length=200)
    description = models.TextField()
    coach = models.ForeignKey(Coach, null=True, blank=True, related_name='coach_courses')
    assistant = models.ForeignKey(Coach, null=True, blank=True, related_name='assistant_courses')

    def __unicode__(self):
        return self.name

class Lesson(models.Model):
    subject = models.CharField(max_length=200)
    description = models.TextField()
    course = models.ForeignKey(Course)
    order = models.PositiveIntegerField()

    def get_url(self):
        return reverse_lazy('courses:detail', None, [self.course.id])

    def __unicode__(self):
        return self.subject

courses/forms.py
from django import forms
from courses.models import Course, Lesson

class CourseModelForm(forms.ModelForm):
    class Meta:
        model = Course
        fields = '__all__'

class LessonModelForm(forms.ModelForm):
    class Meta:
        model = Lesson
        fields = '__all__'

courses/views.py
from django.core.urlresolvers import reverse_lazy
from django.contrib import messages
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from courses.models import Course, Lesson
from pybursa.views import MixinMsg, MixinTitle

import logging
course_logger = logging.getLogger(__name__)


class CourseDetailView(DetailView):
    model = Course
    template_name = 'courses/detail.html'
    context_object_name = 'course'

    def get_context_data(self, **kwargs):
        data = super(CourseDetailView, self).get_context_data(**kwargs)
        lessons = Lesson.objects.filter(course=self.object).order_by('order')
        data['lessons'] = lessons

        #logger
        #course_logger.debug("Courses detail view has been debugged")
        #course_logger.info("Logger of courses detail view informs you!")
        #course_logger.warning("Logger of courses detail view warns you!")
        #course_logger.error("Courses detail view went wrong!")

        return data

class CourseCreateView(CreateView):
    model = Course
    success_url = reverse_lazy('index')
    template_name = 'courses/add.html'
    context_object_name = 'course'

    def get_context_data(self, **kwargs):
        data = super(CourseCreateView, self).get_context_data(**kwargs)
        data['title'] = 'Course creation'
        return data

    def form_valid(self, form):
        form.save()
        messages.success(self.request, 'Course %s has been successfully added.' % form.cleaned_data['name'])
        return super(CourseCreateView, self).form_valid(form)

class CourseUpdateView(UpdateView):
    model = Course
    template_name = 'courses/edit.html'
    context_object_name = 'course'

    def get_context_data(self, **kwargs):
        data = super(CourseUpdateView, self).get_context_data(**kwargs)
        data['title'] = 'Course update'
        return data

    def form_valid(self, form):
        form.save()
        messages.success(self.request, 'The changes have been saved.')
        return super(CourseUpdateView, self).form_valid(form)

    def get_success_url(self):
        return reverse_lazy('courses:edit', None, [self.object.id])

class CourseDeleteView(DeleteView):
    model = Course
    success_url = reverse_lazy('index')
    template_name = 'courses/remove.html'
    context_object_name = 'course'

    def get_context_data(self, **kwargs):
        data = super(CourseDeleteView, self).get_context_data(**kwargs)
        data['title'] = 'Course deletion'
        return data

    def delete(self, request, *args, **kwargs):
        ret_msg = super(CourseDeleteView, self).delete(request, *args, **kwargs)
        messages.success(self.request, 'Course %s has been deleted.' % (self.object.name))
        return ret_msg

class LessonCreateView(MixinMsg, MixinTitle, CreateView):
    model = Lesson
    template_name = 'courses/add_lesson.html'
    context_object_name = 'lesson'
    title = 'Lesson creation'
    success_message = {'msg': 'Lesson %s has been successfully added.', 'attr': 'subject'}

    def get_success_url(self):
        return self.object.get_url()

    def get_initial(self):
        return {'course': self.kwargs['pk']}

templates/courses/add.html
{% extends "base.html" %}

{% load staticfiles %}

{% block title %}IT courses add courses page{% endblock title %}

{% block navi %}
    {% include "include/navi_include.html" with active_students="active" %}
{% endblock navi %}

{% block content %}

    <div class="page-header">
        <h3>{{ title }}</h3>
    </div>

    <div>

        <form method="post">
            {% csrf_token %}
            <table>
                {{ form.as_table }}
            </table>
            <input type="submit" value="Добавить"/>
        </form>

    </div>

{% endblock content %}

templates/courses/add_lesson.html
{% extends "base.html" %}

{% load staticfiles %}

{% block title %}IT courses add lesson page{% endblock title %}

{% block navi %}
    {% include "include/navi_include.html" with active_students="active" %}
{% endblock navi %}

{% block content %}

    <div class="page-header">
        <h3>{{ title }}</h3>
    </div>

    <div>

        <form method="post">
            {% csrf_token %}
            <table>
                {{ form.as_table }}
            </table>
            <input type="submit" value="Добавить"/>
        </form>

    </div>

{% endblock content %}

templates/courses/detail.html
{% extends "base.html" %}

{% load staticfiles %}

{% block title %}IT courses course detail page{% endblock title %}

{% block navi %}
    {% include "include/navi_include.html" with course_id_param="?course_id=" course_id=course.id %}
{% endblock navi %}

{% block content %}

    <div id="tf-contact" class="text-center">
        <div class="container">
            <div class="section-title center">
                <h2>{{ title }}</h2>
                <h4>{{ course }}</h4>
                <div class="line">
                    <hr>
                </div>
                <div class="clearfix"></div>
                <small><em>{{ course.description|truncatechars:32 }}</em></small>
            </div>

            <div id="team" class="owl-carousel owl-theme row">
                <div class="item">
                    <div class="thumbnail">
                        <img src="{% static 'img/team/01.jpg' %}" alt="..." class="img-circle team-img">
                        <div class="caption">
                            <a href="{% url 'coaches:detail' course.coach.id %}">
                                <h3>{{ course.coach.first_name }} {{ course.coach.last_name }}</h3>
                            </a>
                            <p>Учитель</p>
                            <p>{{ course.coach.description }}</p>
                        </div>
                    </div>
                </div>

                <div class="item">
                    <div class="thumbnail">
                        <img src="{% static 'img/team/03.jpg' %}" alt="..." class="img-circle team-img">
                        <div class="caption">
                            <a href="{% url 'coaches:detail' course.assistant.id %}">
                                <h3>{{ course.assistant.first_name }} {{ course.assistant.last_name }}</h3>
                            </a>
                            <p>Ассистент</p>
                            <p>{{ course.assistant.description }}</p>
                        </div>
                    </div>
                </div>
            </div>

            <h3>План курса</h3>
            <a href="{% url 'courses:add-lesson' course.id %}">добавить занятие</a>

            <table class="table table-striped table-bordered">
                <tr>
                    <th>#</th>
                    <th>Тема</th>
                    <th>Описание</th>
                </tr>
                {% for lesson in lessons %}
                    <tr>
                        <td>{{ lesson.order }}</td>
                        <td>{{ lesson }}</td>
                        <td>{{ lesson.description }}</td>
                    </tr>
                {% endfor %}
            </table>

        </div>
    </div>

{% endblock content %}

templates/courses/edit.html
{% extends "base.html" %}

{% load staticfiles %}

{% block title %}IT courses edit courses page{% endblock title %}

{% block navi %}
    {% include "include/navi_include.html" with active_students="active" %}
{% endblock navi %}

{% block content %}

    <div class="page-header">
        <h3>{{ title }}</h3>
    </div>

    <div>

        <form method="post">
            {% csrf_token %}
            <table>
                {{ form.as_table }}
            </table>
            <input type="submit" value="Сохранить"/>
        </form>

    </div>

{% endblock content %}

templates/courses/remove.html
{% extends "base.html" %}

{% load staticfiles %}

{% block title %}IT courses delete courses page{% endblock title %}

{% block navi %}
    {% include "include/navi_include.html" with active_students="active" %}
{% endblock navi %}

{% block content %}

    <div class="page-header">
        <h3>{{ title }}</h3>
    </div>

    <div>

        <h4>Курс {{ course.name }} будет удален</h4>
        <form method="post">
            {% csrf_token %}
            <input type="submit" value="Удалить" />
        </form>

    </div>

{% endblock content %}