coaches/urls.py
from django.conf.urls import patterns, url

from coaches import views

urlpatterns = patterns('',
    url(r'^(?P<coach_id>\d+)/$', views.detail, name='detail'),
)

polls/urls.py
from django.conf.urls import patterns, url

from polls import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^specifics/(?P<question_id>\d+)/$', views.detail, name='detail'),
    url(r'^(?P<question_id>\d+)/results/$', views.results, name='results'),
    url(r'^(?P<question_id>\d+)/vote/$', views.vote, name='vote'),
)

pybursa/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.http import HttpResponse

from pybursa import views
from feedbacks.views import FeedbackView

def index(request):
    return HttpResponse('hello')

urlpatterns = patterns('',
    url(r'^polls/', include('polls.urls', namespace="polls")),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', views.index, name='index'),
    url(r'^contact/$', views.contact, name='contact'),
    url(r'^student_list/$', views.student_list, name='student_list'),
    url(r'^student_detail/$', views.student_detail, name='student_detail'),
    url(r'^student_detail/$', views.student_detail, name='student_detail'),
    url(r'^quadratic/', include('quadratic.urls'), name='quadratic'),

    url(r'^courses/', include('courses.urls', namespace="courses")),
    url(r'^/courses/', include('courses.urls', namespace="courses")),
    url(r'^students/', include('students.urls', namespace="students")),
    url(r'^coaches/', include('coaches.urls', namespace="coaches")),

    url(r'^feedback/$', FeedbackView.as_view(), name='feedback'),
)

students/urls.py
from django.conf.urls import patterns, url
from students.views import StudentDetailView, StudentListView, \
    StudentCreateView, StudentUpdateView, StudentDeleteView




urlpatterns = patterns('',
    url(r'^$', StudentListView.as_view(), name='list_view'),
    url(r'^(?P<pk>\d+)/$', StudentDetailView.as_view(), name='detail'),
    url(r'^add/$', StudentCreateView.as_view(), name='add'),
    url(r'^edit/(?P<pk>\d+)/$', StudentUpdateView.as_view(), name='edit'),
    url(r'^remove/(?P<pk>\d+)/$', StudentDeleteView.as_view(), name='remove')
)

coaches/models.py
from django.db import models
from django.contrib.auth.models import User

class Coach(models.Model):
    user = models.OneToOneField(User)
    date_of_birth = models.DateField()
    gender = models.CharField(max_length=1, choices=(('M', 'Male'), ('F', 'Female')))
    phone = models.CharField(max_length=60)
    address = models.CharField(max_length=200)
    skype = models.CharField(max_length=100)
    description = models.TextField()

    def __unicode__(self):
        return self.user.username

    def _get_first_name(self):
        return self.user.first_name

    def _get_last_name(self):
        return self.user.last_name

    first_name = property(_get_first_name)
    last_name = property(_get_last_name)

coaches/views.py
from django.shortcuts import render
from coaches.models import Coach

def detail(request, coach_id):
    coach = Coach.objects.get(id=coach_id)
    data = {'coach': coach}
    return render(request, 'coaches/detail.html', data)

templates/coaches/detail.html
{% extends "base.html" %}

{% load staticfiles %}

{% block title %}IT courses coaches detail page{% endblock title %}

{% block navi %}
    {% include "include/navi_include.html" with active_coaches="active" %}
{% endblock navi %}

{% block content %}

    <div class="page-header">
        <h1 class="detail-surname">{{ coach.first_name}} {{coach.last_name}}</h1>
    </div>

    <div>
        <table class="table detail-table">
            <tr>
                <th>дата рождения</th>
                <td>{{ coach.date_of_birth|date:"d F, Y" }}</td>
            </tr>
            <tr>
                <th>адрес</th>
                <td>{{ coach.address }}</td>
            </tr>
            <tr>
                <th>почта</th>
                <td>{{ coach.user.email }}</td>
            </tr>
            <tr>
                <th>логин skype</th>
                <td>{{ coach.skype }}</td>
            </tr>
            <tr>
                <th>телефон</th>
                <td>{{ coach.phone }}</td>
            </tr>
            <tr>
                <th>курсы учитель</th>
                <td>
                    <ul>
                        {% for course in coach.coach_courses.all %}
                        <li><a href="{% url 'courses:detail' course.id %}">{{ course }}</a>

                            <p>студенты курса <a href="{% url 'students:list_view' %}?course_id={{ course.id }}">
                                <span class="glyphicon glyphicon-user"></span>
                            </a></p>
                        </li>
                        {% endfor %}
                    </ul>
                </td>
            </tr>

            <tr>
                <th>курсы ассистент</th>
                <td>
                    <ul>
                        {% for course in coach.assistant_courses.all %}
                        <li><a href="{% url 'courses:detail' course.id %}">{{ course }}</a>

                            <p>студенты курса <a href="{% url 'students:list_view' %}?course_id={{ course.id }}">
                                <span class="glyphicon glyphicon-user"></span>
                            </a></p>
                        </li>
                        {% endfor %}
                    </ul>
                </td>
            </tr>

        </table>
    </div>

{% endblock content %}